backend/backend/urls.py
from django.contrib import admin
from django.urls import path,include
from form import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('form.urls')),
]

backend/form/urls.py
from django.urls import include, path
from . import views
from datetime import datetime,timedelta 
import requests
from .models import Slots, Course, TimeSlots

urlpatterns = [
    path('add/', views.trialclasscreate, name='trialclass_add'),
    path('ajax/load-slots/', views.load_slots, name='ajax_load_slots'),
    path('ajax/load-time_slots/', views.load_time_slots, name='ajax_load_time_slots'),

]

# def getchoice(j):

#     r = requests.get('https://script.googleusercontent.com/macros/echo?user_content_key=3QIfSWtbjynPofOnfE_8SugMIs8YRFwsbsAXMR-oZBO0goj1E7OjSM0X3RyL6PPBmKhputy-Kxbuz4PaAoWQ5BFhcqqesPwum5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnC09Nb0QZ6ca_LU0vmo6mSiQ7SyFG3CgdL9-1Vgcha-TAYaAGhh-9xNG-9rMNEZHQRElvdDletx0&lib=MlJcTt87ug5f_XmzO-tnIbN3yFe7Nfhi6')
#     Choice =  (r.json()) 
#     course_name = Choice[j]['course_name']
#     x = len(Choice[j]['slots'])
#     date = []
#     time = []
#     for i in range(x):
#         your_dt = datetime.fromtimestamp(int(Choice[j]['slots'][i]['slot'])/1000)
#         slot_date = (your_dt.strftime("%Y-%m-%d"))
#         date.append(slot_date)
#         slot_time = (your_dt.strftime("%H:%M:%S"))
#         time.append(slot_time)
#     course = Course.objects.get(name=course_name)
#     distinct_date = set(date)
    
#     for d in (distinct_date):
#         slot_save = Slots.objects.create(course=course,slot_date=d)
#         print(slot_save)
#         slot_save.save()

#     for i in range(len(time)):
#         print(date[i])
#         print(time[i])
#         slot = Slots.objects.filter(slot_date=date[i])
#         for j in range(len(slot)):
#             time_slot = TimeSlots.objects.create(slot=slot[j],time_slot=time[i])
#             time_slot.save()



# for r in range(5):
#     getchoice(r)

backend/form/models.py
from datetime import datetime,timedelta 
from django.db import models
import requests



class Course(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Slots(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    slot_date = models.DateField(default=datetime.now().date)

    def __str__(self):
        return str(self.slot_date)

class TimeSlots(models.Model):
    slot = models.ForeignKey(Slots, on_delete=models.CASCADE)
    time_slot = models.TimeField(default=datetime.now().time)

    def __str__(self):
        return str(self.slot)+'-'+str(self.time_slot)

class TrialClass(models.Model):

    parents_name = models.CharField(max_length=50,null=False)
    parents_contact_no = models.CharField(max_length=10,null=False)
    parents_email_id = models.EmailField(null=False)
    child_name = models.CharField(max_length=50,null=False)
    child_age = models.IntegerField(null=False)
    course = models.ForeignKey(Course,on_delete=models.SET_NULL, null=True)
    slot = models.ForeignKey(Slots,on_delete=models.SET_NULL, null=True)
    time_slot = models.ForeignKey(TimeSlots,on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.child_name

backend/form/forms.py
from django import forms
from .models import TrialClass,Slots,TimeSlots

class TrialClassForm(forms.ModelForm):
    class Meta:
        model = TrialClass
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['slot'].queryset = Slots.objects.none()


        if 'course' in self.data:
            try:
                course_id = int(self.data.get('course'))
                print(course_id)
                self.fields['slot'].queryset = Slots.objects.filter(course_id=course_id).order_by('slot_date')
            except (ValueError, TypeError):
                pass  
        elif self.instance.pk:
            self.fields['slot'].queryset = self.instance.course.slot_set.order_by('slot_date')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['time_slot'].queryset = TimeSlots.objects.none()


        if 'slot' in self.data:
            try:
                slot_id = int(self.data.get('slot'))
                print(slot_id)
                self.fields['time_slot'].queryset = TimeSlots.objects.filter(slot_id=slot_id).order_by('time_slot')
            except (ValueError, TypeError):
                pass  
        elif self.instance.pk:
            self.fields['time_slot'].queryset = self.instance.slot.time_slot_set.order_by('time_slot')

        

backend/form/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from .models import TrialClass,Slots,TimeSlots
from .forms import TrialClassForm
from datetime import datetime,timedelta,date


def trialclasscreate(request):
    if request.method == 'POST':
        form = TrialClassForm(request.POST)
        if form.is_valid():
            print("go")
            form.save(commit=True)
            form = TrialClassForm()
        else:
            print("stop")
            print (form.errors)
    else:
        form = TrialClassForm()
    return render(request, 'form/trialclass_form.html', {'form': form})

def load_slots(request):
    course_id = request.GET.get('course')
    """
    Here to show that the latest slot to be fetched 
    upto max. 7 days from now, I have taken 2020-04-27
    as current date. Now it fetches all the days upto 7 
    days from 27th April i.e upto 4th May. All slots with
    dates greater than 4th May is not fetched.
    """
    current_day = datetime.today()-timedelta(days=11)
    time_gap = current_day + timedelta(days=7)
    slots = Slots.objects.filter(course_id=course_id)
    slots_within_range = slots.filter(slot_date__lte=time_gap)
    if slots_within_range is None:
        slots_within_range.slot_date = 'No slot during current day'
    return render(request, 'form/date_options.html', {'slots': slots_within_range})

def load_time_slots(request):
    slot_id = request.GET.get('slot')
    x = Slots.objects.get(id=slot_id)
    current_day = (datetime.today()).strftime("%Y-%m-%d")
    # current_day = (datetime.today()-timedelta(days=4)).strftime("%Y-%m-%d")
    """
    This if statement makes sure that slot date
    is chosen as current date, then time slot should be minimum 4 hours from now
    else retrieve all time slots
    """
    if(str(current_day)==str(x)):
        time_gap2 = datetime.now()+timedelta(hours=4)
        slots = TimeSlots.objects.filter(slot_id=slot_id)
        slots_within_time_range = slots.filter(time_slot__gte=time_gap2)
    else:
        slots_within_time_range = TimeSlots.objects.filter(slot_id=slot_id)

    return render(request, 'form/time_options.html', {'slots': slots_within_time_range})

backend/form/templates/form/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

backend/form/templates/form/city_dropdown_list_options.html
<option value="">---------</option>
{% for slot in slots %}
<option value="{{ slot.pk }}">{{ slot.slot_date }}</option>
{% endfor %}

backend/form/templates/form/date_options.html
<option value="">---------</option>
{% for slot in slots %}
<option value="{{ slot.pk }}">{{ slot.slot_date }}</option>
{% endfor %}

backend/form/templates/form/time_options.html
<option value="">---------</option>
{% if slots %}
{% for slot in slots %}
<option value="{{ slot.pk }}">{{ slot.time_slot }}</option>
{% endfor%}
{% else %}
<script>alert("No time slots for today. Chose any other date")</script>
{% endif %}

backend/form/templates/form/trialclass_form.html
{% extends './base.html' %}
{% load crispy_forms_tags %}
{% block content %}


  <form method="post" id="trialclassForm" data-slots-url="{% url 'ajax_load_slots' %}" data-timeslots-url="{% url 'ajax_load_time_slots' %}" novalidate>

    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success" value="Reset form">Submit</button>
  </form>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
   
    $("#id_course").change(function () {
      var url = $("#trialclassForm").attr("data-slots-url");
      var courseId = $(this).val();
      console.log(courseId);

      $.ajax({
        url: url,
        data: {
          'course': courseId
        },
        success: function (data) {
          $("#id_slot").html(data);
        }
      });

    $("#id_slot").change(function () {
      var url2 = $("#trialclassForm").attr("data-timeslots-url");
      var slotId = $(this).val();
      console.log(slotId)


      $.ajax({
        url: url2,
        data: {
          'slot': slotId
        },
        success: function (data) {
          $("#id_time_slot").html(data);
        }
      })
    });

    });
  </script>

{% endblock %}

backend/templates/form/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>NotchUp</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8" style="margin:30px 80px 40px 20px" text-align="center">
          <h1 class="mt-2"  >NotchUp Trail Class</h1>
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>